### ISSUE TITLE
how to run/deploy template locally

### ISSUE THREAD

**Issue by 0xkelvin** [uideck/docs#1]
i bought your css template, i can not find the command to run/deploy it locally in your document

please help

<img width="805" alt="image" src="https://user-images.githubusercontent.com/56182747/180969784-f8a1194a-8616-47b3-97a3-9776e5fa1b56.png">

**Comment by Musharofchy** [comment]
Not sure how this issue gone missing from notification, extremely sorry for this. Kindly follow: https://docs.uideck.com/tailwind-template we have simplified the process and changed the workflow
